### ISSUE TITLE
what's the usage scenarios

### ISSUE THREAD

**Issue by masterchen** [Revalcon/MQTTnet.EventBus#3]
This extension seems good, can you give some examples on in which case we need eventbus?

And , i cann't  launch MQTTnet.EventBus.AspNetCoreApi_Integration project, maybe because  the ip Address ,can you give some guide ? Thanks 

------i changed the ip form {IP Address}  to  localhost
            services.AddMqttEventBus(cfg =>
            {
                cfg
                    .WithClientId("Api")
                    .WithTcpServer("127.0.0.1", 1883);

            }, retryCount

**Comment by arttonoyan** [comment]
First you should install the message broker or you can use online free servers for it ( http://test.mosquitto.org ). The {IP Address} and { PORT } intended for broker, so if you have installed it on your local machine the ip can be '127.0.0.1' otherwise it should refer to broker server. Also please be aware that client id should be unique for each client ( otherwise the connection will be closed by server).
This project wraps https://github.com/chkr1011/MQTTnet framework for facilitate the integration into custom ASP.NET Core projects. You can find more info about MQTTTnet and it's usage in that repo.
